---
title: "Complex in-built objects in R"
author: "Luciano Gabbanelli"
date: "2022-10-10"
output:
  html_document:
    toc: true
    toc_float: true
    collapse: true
    smooth_scroll: true
    theme: journal
    highlight: kate
    df_print: paged
    code_folding: show
---

# Functions

## 1. Median
```{r}

my.median <- function(my.vec){
  
  if (length(my.vec) %% 2 != 0) return( my.vec[ceiling(length(my.vec)/2)] )
  else return( `+`(my.vec[length(my.vec)/2],my.vec[length(my.vec)/2+1])/2 )
}

a.vector <- c(1,6,3,8,5,2,7,5,1)
b.vector <- c(1,6,3,8,5,2,7,5,1,11)

my.median(a.vector)
my.median(b.vector)

```

## 2. Factorial

```{r}

factorial(3)
factorial(4)
factorial(1)
factorial(0)
factorial(-1)

my.factorial <- function(){
  n <- as.integer(readline("Introduce a number: "))
  if (n < 0) {
    print("The factorial function is not defined for negative integers.")
  } else if (n==0){
    return(1)
  } else {
    return(cat(n, "! =", prod(c(1:n))))
  }
}

my.factorial()


recursive.factorial <- function(x) {
  if (x < 0) print("The factoril is only defined for positive numbers.")
  else if (x == 0)    return (1)
  else return (x * recursive.factorial(x-1))
}

recursive.factorial(-1)


```



## 3. Statistics

```{r}

my.vector <- sample(1:1000000, 100000, replace = F)

statistics <- function(input.vector){
  # List where to store the results:
  result.list <- list()
  # Vector length:
  result.list$length <- length(my.vector)
  # Minimum value of the vector:
  result.list$minimum <- min(my.vector)
  # Maximum value of the vector.
  result.list$maximum <- max(my.vector)
  # Vector mean:
  result.list$mean <- mean(my.vector)
  # Vector median:
  result.list$median <- my.median(my.vector)
  # Standard deviation of the vector:
  result.list$strdev <- sd(my.vector)
  # Sum of the vector components:
  result.list$sum <- sum(my.vector)
  # Cumulative vector sum:
  # Be careful with the warning!!
  # Integer overflow in 'cumsum'; use 'cumsum(as.numeric(.))'$longitud
  result.list$suma_acumulada <- cumsum(as.numeric(my.vector))
  # Returns the list with the statistics:
  return(result.list)
}

my.statistics <- statistics(my.vector)
my.statistics
length(my.statistics)
length(my.statistics[[8]]) == my.statistics$length

```



## 4. Normal distribution with modulus less (or equal) than one

```{r}

my.list <- list()

repeat {
  x <- rnorm(1)
  if (abs(x) > 1){
    break
  }
  my.list <- append(my.list,x)
}

my.list

```



## 5. Armstrong number

```{r}

armstrong <- function(){
  num_str = readline(prompt="Enter a number: ")
  num_list = unlist(strsplit(num_str, split=""))
  sum = 0
  for (digit in num_list){
    sum <- sum + as.integer(digit)^length(num_list)
  }
  if(as.integer(num_str) == sum) {
    return(paste(num_str, "is an Armstrong number."))
    } else {
    return(paste(num_str, "is not an Armstrong number."))
    }
}

armstrong()

armstrong2 <- function(num){
  num_list = unlist(strsplit(toString(num), split=""))
  sum = 0
  for (digit in num_list){
    sum <- sum + as.integer(digit)^length(num_list)
  }
  if(num == sum) {
    return (expected=TRUE)
    } else {
    return(expected=FALSE)
    }
}

armstrong2(1634)

```



## 6. Eratostenes

```{r}

eratostenes <- function(n) {
  if (n >= 2) {
    x = seq(2, n)
    prime_nums = c()

    for (i in seq(2, n)) {
      if (any(x == i)) {
        prime_nums = c(prime_nums, i)
        x = c(x[(x %% i) != 0], i)
      }
    }
    return(prime_nums)
  } else {
    stop("Input number should be at least 2.")
  }
} 

eratostenes(120)
```
